name: CI Checks
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run ci
        env:
          EXTERNAL_DRIVE_ROOT: "/example-root"
